### ISSUE TITLE
Broken mentions

### ISSUE THREAD

**Issue by teammate165** [marnixah/xi-jinping-bot#9]
Some words such as n-bomb makes the bot respond with a broken mention, I assume this is an older response? Here's an example:

![image](https://user-images.githubusercontent.com/57411375/141307798-960c5264-cce8-478f-b28a-8d45e436018e.png)

**Comment by marnixah** [comment]
GitHub autoclosed the issue for some reason, but it is most definitely still there. Will try and look into it more today

**Comment by marnixah** [comment]
I have further looked into this, and it seems to be an issue with the way this project deals with numbers... User id's are parsed as numbers, which javascript put as floating point numbers. This means all my data so far has errors in it, and I am giving up on this project.

**Comment by marnixah** [comment]
I have further looked into further looking into this and have a potential fix. It won't be pretty, but this is what happens if you have older code that broke😄
